// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxciajvfftcwrppjlkin.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4Y2lhanZmZnRjd3JwcGpsa2luIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NTI4NDcsImV4cCI6MjA2MzQyODg0N30.3YYnzXBYWAqpCy1s8E3ITTSEohlgcenqsxAkxZslyfY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);